### ISSUE TITLE
请问能在需要加菜单的插件外自定义菜单吗

### ISSUE THREAD

**Issue by SnowMoonSS** [hamo-reid/nonenot_plugin_PicMenu#10]
有的插件为了更新方便是使用`nb install`安装的，修改这样的插件有点不太方便。而且这些插件对于命令的处理各式各样，该如何对自动生成的菜单进行修改……
或者这样独立于其他插件的完全自定义菜单的方法其实是有的……请告知一下，谢谢！

**Comment by hamo-reid** [comment]
目前还没有除直接修改源码之外的方法

但是通过外置文件加载菜单的方式在更新计划中，会在下版本中实现

**Comment by hamo-reid** [comment]
在插件代码外定义菜单的方法已实现

更新插件即可

```
pip install --upgrade nonebot_plugin_PicMenu
```

具体使用方法参考README

**Comment by SnowMoonSS** [comment]
好！成了！
之前一直用`-`，今天开窍看到是`_`……
看起来只支持同一个nonebot实例中的插件，但至少是有了。
希望之后能支持彻底的自定义，就算是配置文件的名称与已装插件不匹配也能加载进图形菜单，这样就能给mirai插件也写个菜单了，同时缝合别的bot也更简单了
总之感谢dalao
