### ISSUE TITLE
重启bot后显示OSError: unknown file format

### ISSUE THREAD

**Issue by xiaoyang212** [hamo-reid/nonenot_plugin_PicMenu#11]
请问这种情况改如何解决？
![微信图片_20220922171526](https://user-images.githubusercontent.com/83319298/191708315-b3819211-eb67-4960-accb-70cb7a2fbea2.jpg)

**Comment by hamo-reid** [comment]
一般是文件格式不支持导致的，可以尝试更换下字体文件
