### ISSUE TITLE
富文本解析问题

### ISSUE THREAD

**Issue by lgc2333** [hamo-reid/nonenot_plugin_PicMenu#12]
如图
![image](https://user-images.githubusercontent.com/59048777/198836301-44dbddcd-073e-4ac8-bd92-618101e4ca3d.png)
![image](https://user-images.githubusercontent.com/59048777/198836333-682f9c0c-8ae0-4bb4-a1f2-16e68766fd33.png)
将`<序号>`中的`<` `>`去掉即可显示
是否考虑添加`&lt;` `&gt;`这样的转义表达

**Comment by lgc2333** [comment]
any update? if no i'll close this issue

**Comment by hamo-reid** [comment]
There won't be any updates in the near future, I'm busy with other projects
