### ISSUE TITLE
帮我看看报错

### ISSUE THREAD

**Issue by Xiao-yux** [hamo-reid/nonenot_plugin_PicMenu#21]
![image](https://user-images.githubusercontent.com/79674967/229697721-ae46a8f6-97e1-410b-995a-1b51bc129d0b.png)
![image](https://user-images.githubusercontent.com/79674967/229697835-029940b6-3a14-4f3a-bcb3-d8b9f0c344dd.png)
那个报错是什么啊，格式错了吗？还是缺了什么东西

**Comment by Yunmo-1** [comment]
上面的解决了
![image](https://user-images.githubusercontent.com/79674967/229700044-109ee275-c90d-4ff1-ad4d-50891dc9ebbc.png)
这个我是不知道怎么解决

**Comment by Xiao-yux** [comment]
上面的解决了

**Comment by Xiao-yux** [comment]
![image](https://user-images.githubusercontent.com/79674967/229700209-3582e1be-f30a-481e-ac87-74e3528afc15.png)
这个键对值一个不能少吗

**Comment by Xiao-yux** [comment]
也用不到这么多

**Comment by Xiao-yux** [comment]
这个东西不能高度自定义吗？
"自定义头部名称":"信息",

还有能把排序也弄成手动的吗，给了序号就按给的在菜单排序，没给的就自动分配。这样的

**Comment by hamo-reid** [comment]
因为是Pillow手搓的，功能和渲染是高度耦合的，修改功能是比较麻烦的

想重构想了很久都没什么思路

比较现实的方案是使用浏览器渲染，将模板逻辑和数据层分离，但是那样就会多个chromium

**Comment by Weltolk** [comment]
> 因为是Pillow手搓的，功能和渲染是高度耦合的，修改功能是比较麻烦的
> 
> 想重构想了很久都没什么思路
> 
> 比较现实的方案是使用浏览器渲染，将模板逻辑和数据层分离，但是那样就会多个chromium

期待按No排序(
