### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Xiao-yux** [hamo-reid/nonenot_plugin_PicMenu#25]
![image](https://user-images.githubusercontent.com/79674967/230262119-0d9045db-d102-4a71-9864-896ed6529750.png)
不知道怎么回事

**Comment by Xiao-yux** [comment]
我就去更新了个米友社签到的插件，然后就崩了

**Comment by hamo-reid** [comment]
某个插件名里有特殊字符，无法用gbk编码排序，比如：“❥”
