### ISSUE TITLE
json 菜单配置文件不加载

### ISSUE THREAD

**Issue by smallcat9669** [hamo-reid/nonenot_plugin_PicMenu#26]
我按照例子写了一个投骰子的配置文件，但是不知道它为何没有加载上
![image](https://github.com/hamo-reid/nonebot_plugin_PicMenu/assets/114364961/54e57754-4682-4b96-8f3a-f936fb781f08)

![image](https://github.com/hamo-reid/nonebot_plugin_PicMenu/assets/114364961/bcdf5880-5988-4398-a262-4567dfb8615d)

这有甚么办法解决吗？

**Comment by hamo-reid** [comment]
请检查一下JSON存放路径是否和readme说明相同

**Comment by smallcat9669** [comment]
> 请检查一下JSON存放路径是否和readme说明相同

我是用nb run --reload 命令启动的
路径:
![image](https://github.com/hamo-reid/nonebot_plugin_PicMenu/assets/114364961/c4a83e94-cda0-4999-a066-90a60ab1f7f8)

**Comment by hamo-reid** [comment]
日志能发一下吗

**Comment by smallcat9669** [comment]
![NI%M8(OB~PF YSD DDT@B8I](https://github.com/hamo-reid/nonebot_plugin_PicMenu/assets/114364961/93abe387-e2bb-4b9f-9b6e-b210dd062aa8)

**Comment by hamo-reid** [comment]
插件的逻辑是，只能为已经加载的插件配置菜单，你要保证你要添加菜单的插件成功加载，且插件的名称和你json的文件名完全一致

**Comment by smallcat9669** [comment]
懂了，谢谢
我在看的时候那个插件用的是 _ 符号
我想问题在这里
