### ISSUE TITLE
部分字体出现文字超出现象

### ISSUE THREAD

**Issue by LoCCai** [hamo-reid/nonenot_plugin_PicMenu#3]
建议加一个可调整开关或者接口处理

**Comment by hamo-reid** [comment]
能说明下是哪一级菜单的哪个部分超出
或者发一下出问题的图片

**Comment by LoCCai** [comment]
![MUO3 }L46TTE%9 X65_D3{2](https://user-images.githubusercontent.com/105721394/177382679-eb226b73-ddf1-45f5-9efe-06ced961092e.PNG)

**Comment by hamo-reid** [comment]
了解了，会尽快做出修正

**Comment by LoCCai** [comment]
嗯嗯好哒

**Comment by hamo-reid** [comment]
问题已修复

```
pip install --upgrade nonebot_plugin_PicMenu
```

更新最新 v0.1.3.2即可

**Comment by LoCCai** [comment]
好的，我试试，阿里嘎多

**Comment by LoCCai** [comment]
![image](https://user-images.githubusercontent.com/105721394/177835054-ea5287f8-1c25-4b33-a544-b4a617c26388.png)
出现这个错误

**Comment by hamo-reid** [comment]
> ![image](https://user-images.githubusercontent.com/105721394/177835054-ea5287f8-1c25-4b33-a544-b4a617c26388.png)
> 出现这个错误

是加载的时候出现的还是使用时出现的，我这边测试时是没有问题的

**Comment by LoCCai** [comment]
使用的时候，我有用那个派蒙的插件，是和它的插件信息不兼容了吗？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月8日 1:43
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [hamo-reid/nonenot_plugin_PicMenu] 部分字体出现文字超出现象 (Issue #3)


[image]<https://user-images.githubusercontent.com/105721394/177835054-ea5287f8-1c25-4b33-a544-b4a617c26388.png>
出现这个错误

是加载的时候出现的还是使用时出现的，我这边测试时是没有问题的

―

**Comment by hamo-reid** [comment]
报错这一行是加载没有menu_data的插件触发的

通过nonebot.plugin.get_plugin()获取插件对象，传入参数是加载的插件名（不是metadata里的插件名），返回空值说明查找不到插件

**Comment by hamo-reid** [comment]
我再做下测试吧

**Comment by hamo-reid** [comment]
![~ B7WM`W2~R((SW0_G$8CHJ](https://user-images.githubusercontent.com/61297321/177839676-d8feb7f8-c227-4481-b248-a9d552313efe.gif)

好像确实有问题

**Comment by LoCCai** [comment]
就是说，我要把每个我加载的插件都写好帮助文档对吗

**Comment by LoCCai** [comment]
大佬加油，我扛不住先睡了，明天我有时间把我模块的功能啥的写完文档然后看看

**Comment by hamo-reid** [comment]
我的设计是不用的，有基础的metadata就可以

但是确实有问题

**Comment by hamo-reid** [comment]
已修复，pip更新至最新版v0.1.4就可以了

**Comment by LoCCai** [comment]
好耶，已经可以了
