### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Astolfocat** [hamo-reid/nonenot_plugin_PicMenu#4]
很多使用的群友只知道发送[菜单]可以查看插件总表，但是不知道如何查看具体插件的使用命令。而本插件的使用方法又需要进入具体插件里面看，就会陷入死循环。
因此是否可以把使用方法[菜单 插件名/插件序号]放在首页标题下方，让群友只发送[菜单]就知道如何使用菜单插件呢？

**Comment by hamo-reid** [comment]
新版本已添加使用[菜单 PicMenu]命令查看菜单详细使用方法的指向性提示

更新插件即可
```powershell
pip install --upgrade nonebot_plugin_PicMenu
```
