### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by jasmineamber** [hamo-reid/nonenot_plugin_PicMenu#8]
插件很实用, 在此基础上做了一些修改
改动的原因:
1. `trigger_method` 对于普通用户来说并不懂是什么意思
2. `func` 似乎和 `brief_des` 重复了
3. `usage` 似乎没有展示的必要, 二级菜单有关于命令的描述
4. 有必要告知普通用户怎么触发命令: 比如是否有权限, 是否需要@Bot
5. 本插件的菜单似乎没有必要展示, 普通用户不知道怎么使用展示了也没什么用

目前改成了下这样(插件改成了服务, 是我本身Bot的需要, 请忽略), 作者觉得合理的话, 我提个PR
![DCIM](https://user-images.githubusercontent.com/13842833/179198463-86d33948-787c-4c69-9cef-38a6b8bc8a3a.png)
![DCIM(2)](https://user-images.githubusercontent.com/13842833/179198484-98b7ed0d-0008-4dc6-ac26-5c33d54e7be7.png)
![DCIM(1)](https://user-images.githubusercontent.com/13842833/179198504-2458d2cd-fa44-4a1b-b920-7c3488c366c2.png)

**Comment by hamo-reid** [comment]
感谢对插件的建议，以下是我设计时的考虑
1. 关于表格条目
    表格内所含条目很难权衡，早期版本（old分支）采取的是与建议中相似的条目结构。

    但是考虑到，不是插件所有的功能都是通过命令触发的，例如：定时任务，戳一戳，或者on_notice相关触发的功能，同时因为用命令进行检索和模糊匹配的话有误触的可能。

    所以将表格条目更改成了 **功能 触发方式 触发条件 简述** 的形式来提高意义上的兼容性，信息没有硬性规定，开发者可以根据需求在触发条件和触发方式中填写信息，比如权限或是否at可以写入触发条件

2. `func`和`brief_des`重复的问题
    插件的模糊匹配需要一个类似于键作用的值，`func`承担了这个角色，一般来说会较为简短，而`brief_des`作为补充说明功能

3. usage
    usage的展示是为了兼容仅有基础metadata信息的插件进行的格式统一，也为了更方便的去得知插件使用方法

因此表格条目和usage可能不会做改动

但是会对metadata的内容进行修改，更好说明本插件的功能和使用方法

同时会在一级菜单提供指向菜单使用方法的说明，以及在一、二级菜单中添加表头

改动会在下版本实现
