### ISSUE TITLE
用插件名查询时一直提示`插件名过于模糊或不存在`

### ISSUE THREAD

**Issue by lgc2333** [hamo-reid/nonenot_plugin_PicMenu#9]
![image](https://user-images.githubusercontent.com/59048777/182560527-baa1695b-0ce8-4306-a5d4-0b9d9cdff4aa.png)
![image](https://user-images.githubusercontent.com/59048777/182560556-c0faee64-566c-4897-bbd4-314a7f219cdc.png)

能不能支持一下不带空格和自定义指令前缀……
可以试试看用这个 https://v2.nonebot.dev/docs/tutorial/plugin/create-handler#commandarg

**Comment by hamo-reid** [comment]
插件名查询时 提示`插件名过于模糊或不存在`的问题已经修复

更新插件即可
```powershell
pip install --upgrade nonebot_plugin_PicMenu
```
响应器相关的更改暂不考虑，后续版本可能实现
